# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('date', models.DateTimeField()),
                ('image_item', models.ImageField(upload_to=b'')),
                ('logo', models.ImageField(upload_to=b'')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
