# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 21:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supp',
            fields=[
                ('supplier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='display.Supplier')),
            ],
            bases=('display.supplier',),
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='username',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='image_item',
            new_name='image',
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 1, 10, 21, 38, 55, 493547, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
